# Configuraes de desenvolvimento

# Conexo com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/marmitaria
spring.datasource.username=root
spring.datasource.password=1234

# Recriar banco de dados ao iniciar aplicao: sempre
spring.sql.init.mode=always

# Mostrar SQL gerado pelo JPA nos logs
spring.jpa.show-sql=true
